ECG Rpeak DataStream created
MD2Korg/CerebralCortex-2.0-legacy pull request #1
Opened 2017-01-15 03:20 UTC by aungkonazim

Respected Dr. Hnat and Dr. Ali,

Please check the main.py ,cStress.py which are changed a bit to run the program
The functions are in 'memphisdataprocessor/preprocessor/' directory
Please check the ecg_processor.py and rpeak_detect.py files

Please let me know if I am lacking in any technical abilities to upload the functions through to you.
Thank you

2017-01-16 18:14 UTC, twhnat requested changes
Please take a look the codacy-bot's comments and resolve these issues.  It enforces good coding practices that we would incorporated into the codebase.

2017-01-16 18:48 UTC, twhnat requested changes

2017-01-16 18:48 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +
Extraneous, please start files with the license block

2017-01-16 18:48 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +                    user: UUID,
Please revert these changes, parameters are expected to be aligned vertically as with the original file.

2017-01-16 18:48 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +                               window_metadata: dict):
Same as above

2017-01-16 18:48 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +        return result
Newline expected at the end of the file

2017-01-16 18:48 UTC, twhnat commented on main.py
> +basedir = "/home/aungkon/Desktop/data/"
Your code changes should be made within the cStress function, this breaks other logic by commenting out code.  If necessary, please create your own test file on which to run

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/cStress.py
> +import numpy as np
This is not part of the requirements.txt file along with scipy.  This has caused the CI server to fail

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/cStress.py
> +def cStress(x):
You have modified the cStress method, this is not to be done as it needs to process all five datstreams.  Please correct this back to the original call parameters

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/ecg_processor.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Copyright year should be 2017

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/ecg_processor.py
> +    '''
Please use the Intellij documentation template to properly comment methods and parameters.  See the other files as reference

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Copyright year needs updated

2017-01-16 18:48 UTC, twhnat commented on main.py
> -        ecgRDD = CC.readfile(find(basedir, {"participant": participant, "datasource": "ecg"})).map(
These should not be commented out

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +def classifyECGwindow(datapoints):
Needs documentation and parameterized

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    # meta = {x[1]}
Remove unused commented code

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +def filterBadECG(datastream: DataStream, windowsize: int = 2000):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +def rr_ave_update(Rpeak_temp1, rr_ave2):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    R=[0]+Rpeak_temp1
What is the intended purpose of this statement?

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    R=[0]+Rpeak_temp1
What does R mean?

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    if len(peak_interval) <= 7:
Hard coded parameters should not be part of these functions.  Constants need to be moved to parameters

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +def detect_Rpeak_firststep(ecgfilteredrdd,fs:int=64,threshold:float=0.5):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    f = 2 / fs
Variables need more descriptive names

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +def ecgpre(rawecg: DataStream):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    from test import CC
Imports do not belong inside of functions.

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/ecgFeaturepre.py
> +    global CC
No global variables

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/ecg_processor.py
> +def filter_bad_ecg(ecg_array,fs):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/ecg_processor.py
> +def compute_rr_datastream(ecg:DataStream,fs:float)->DataStream:
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def rr_interval_update(rpeak_temp1, rr_ave):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def compute_moving_window_int(sample,fs,blackmanWinlen):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +    f = 2 / fs
Variables need more descriptive names

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def compute_r_peaks(rpeak_temp1,pkt_loc,sig_lev,noise_lev,thr1,thr2,rr_ave,mov_win_int_signal,valuepks,pkt):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def check_peak(y,i):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +                sig_lev = 0.125 * mov_win_int_signal[pkt[i]] + 0.875 * sig_lev
An EMWA function should be created to abstract this out

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def remove_close_peaks(rpeak_temp1,sample,fs):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +    def check_min(sample,rpeak_temp1,i):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def confirm_peaks(rpeak_temp1,sample,fs):
Document this function

2017-01-16 18:48 UTC, twhnat commented on memphisdataprocessor/preprocessor/rpeak_detect.py
> +def detect_rpeak(ecg,fs:int=64,threshold:float=0.5):
Document this function

2017-01-19 08:02 UTC, aungkonazim commented
Hi Dr. Hnat,

I have just completed the requisites according to your latest commit. Can you please review the changes.

Thank you

2017-01-19 15:13 UTC, twhnat approved these changes
This looks a lot better.  I am going to work on merging this and will let you know what additional changes are needed.

2017-01-19 15:21 UTC, merged