Functionality windowing
MD2Korg/CerebralCortex-2.0-legacy pull request #2
Opened 2017-01-17 09:14 UTC by Soujanya27

Added the first version of sliding windowing function with a test main.py file. It would be great if you could please review and suggest further improvements.

2017-01-17 15:44 UTC, twhnat requested changes
I have left you some commented that need addressed before we can continue the review process.

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +from cerebralcortex.kernel.datatypes.datastream import DataStream
Please resolve this issue

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +# def window(datastream, windowDataStream):
Commented code does not belong in the files.  It just makes reading code difficult

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +def epochAlign(timestamp, offset, after=False):
Function needs documentation, types, and returns specified.

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +def window_sliding(datastream,window_size,window_offset):
Function needs documentation, types, and returns specified.

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +# def window_sliding(datastream, window_size, window_offset):
Commented code should be removed

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +def windowTime(datastream, windowsize):
Function needs documentation, types, and returns specified.

2017-01-17 15:44 UTC, twhnat commented on main.py
> +basedir = "/home/cloudera/Desktop/data/"
You should not make major modification to the main application that drives testing.  Please introduce tests cases to accomplish this.  These changes in this file need reverted back to the originial

2017-01-17 15:44 UTC, twhnat commented on cerebralcortex/kernel/window.py
> +    timestamps = [d[0] for d in datastream[:len(datastream)]]
I doubt this will work.  DataPoints are what you should be operating with and the returned results should be reflective of this.

2017-01-17 19:41 UTC, nasirali1 requested changes
Please have a look at inline comments.

2017-01-17 19:41 UTC, nasirali1 commented on cerebralcortex/kernel/window.py
> +#     return DataStream()
Please remove commented code before you send a pull request

2017-01-17 19:41 UTC, nasirali1 commented on cerebralcortex/kernel/window.py
> +def window_sliding(datastream,window_size,window_offset):
1 - You can automatically generate basic document code comments by press "alt+enter" in Intellij.
2 - Please be consistent with naming conventions. Use CamelCase (methodName, varName, and ClassName)

2017-01-17 19:41 UTC, nasirali1 commented on cerebralcortex/kernel/window.py
> +    starttime = np.min(timestamps)
Follow NamingConventions. 
startTime

2017-01-17 19:41 UTC, nasirali1 commented on cerebralcortex/kernel/window.py
> +    windowed_datastream = []
NamingConvention!

2017-01-18 18:15 UTC, twhnat commented
Closing due to duplicate pull request #4

2017-01-18 18:15 UTC, closed without merging