New ECG features
MD2Korg/CerebralCortex-2.0-legacy pull request #21
Opened 2017-01-30 23:07 UTC by Soujanya27

2017-01-30 23:33 UTC, twhnat requested changes
I have left some review comments that you should address.  I will look in detail later.

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    f = np.linspace(low_frequency, high_frequency, len(data))
What does f mean?  Choose a better variable name.

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    result_power = 0
Is the default value int or float?

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    Compute Heart Rate Power for specific frequency range
Is there a reference to what this means?  Paper, wikipedia?

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    """
Reference where these default values were derived from and provide a description of this function

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +        rr_VLF_data.append(DataPoint.from_tuple(start_time=key[0], end_time=key[1], sample=heart_rate_power(power,
Can you clean up this line to align the parameters based on the from_tuple method

2017-01-30 23:33 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +        rr_variance_data.append(DataPoint.from_tuple(start_time=key[0], end_time=key[1], sample=np.var(reference_data)))
key[0] and key[1] are used a lot.  Please create a variable to hold these values:

` x, y = key`

2017-01-31 06:42 UTC, Soujanya27 commented on cerebralcortex/data_processor/feature/ecg.py
> +    Compute Heart Rate Power for specific frequency range
Yes it is based on the HRV standard guidelines paper. 
"Heart rate variability: standards of measurement, physiological interpretation and clinical use. Task Force of the European Society of Cardiology and the North American Society of Pacing and Electrophysiology". Shall we mention this somewhere in the code?

2017-01-31 06:43 UTC, Soujanya27 commented on cerebralcortex/data_processor/feature/ecg.py
> +    result_power = 0
It is float.

2017-01-31 06:57 UTC, Soujanya27 commented on cerebralcortex/data_processor/feature/ecg.py
> +        rr_VLF_data.append(DataPoint.from_tuple(start_time=key[0], end_time=key[1], sample=heart_rate_power(power,
Can you please let me know which line you are referring to here?

Thanks

2017-01-31 14:13 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    Compute Heart Rate Power for specific frequency range
Yes.  The comments I leave in reviews should be reflected in code, discussion goes here.

2017-01-31 14:14 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +    result_power = 0
Change the default to `float(0.0)` then.

2017-01-31 14:16 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +        rr_VLF_data.append(DataPoint.from_tuple(start_time=key[0], end_time=key[1], sample=heart_rate_power(power,
Because the lines are so long, try this:

``` 
power, frequency = lomb(data=value, 
                        low_frequency=low_frequency, 
                        high_frequency=high_frequency)
```
Where the parameters are vertically aligned

2017-01-31 15:39 UTC, twhnat commented on cerebralcortex/data_processor/feature/ecg.py
> +        x, y = key
x and y should have a meaning, please be more descriptive of the variable names

2017-01-31 17:18 UTC, twhnat approved these changes
Looks much better

2017-01-31 17:19 UTC, merged