ecg computation finalized
MD2Korg/CerebralCortex-2.0-legacy pull request #26
Opened 2017-02-03 22:22 UTC by aungkonazim

2017-02-06 22:57 UTC, twhnat commented
Per our conversation, please let me know when the test files are corrected and I will merge these test cases into the master

2017-02-07 17:55 UTC, aungkonazim commented
Hi Dr. Hnat,
I have taken some liberty to modify the ecg functions and uploaded the new testing files. Please take a glance and tell me what to change.
Thanks.

2017-02-07 17:56 UTC, twhnat requested changes
Need to fix TravisCI

2017-02-07 17:56 UTC, twhnat commented on cerebralcortex/data_processor/test/test_ecg.py
> +        self._ecg_sample_array = np.genfromtxt(os.getcwd()+'/res/'+'sample_array_ecg.csv',delimiter=',')
You need to utilize this structure for pathing test files:

`os.path.join(os.path.dirname(__file__), 'res/ecg.csv.gz')`

2017-02-07 18:47 UTC, twhnat approved these changes

2017-02-07 18:48 UTC, merged