Datastore engine module
MD2Korg/CerebralCortex-2.0-legacy pull request #5
Opened 2017-01-18 22:25 UTC by nasirali1

Data-store module to read write data/metaData

2017-01-18 22:43 UTC, twhnat requested changes
Needed:
* Schemas for MySQL and Cassandra
* Running example(s)

2017-01-18 22:43 UTC, twhnat commented on README.md
> +* mysql-connector-python==2.0.4
Please place this in the requirements.txt file.

2017-01-18 22:43 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/StoreData/StoreData.py
> +        self.storeData(df, "datapoint2")
Fix this?

2017-01-18 22:43 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/StoreData/StoreMetadat.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Typo in filename.

2017-01-18 22:43 UTC, twhnat commented on .idea/CerebralCortex.iml
>  <module type="JAVA_MODULE" version="4">
Conflict

2017-01-18 22:43 UTC, twhnat commented on .idea/libraries/PySparkLib.xml
> +<component name="libraryTable">
Conflict

2017-01-18 22:43 UTC, twhnat commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Conflict

2017-01-18 22:43 UTC, twhnat commented on .idea/modules.xml
>    <component name="ProjectModuleManager">
Conflict

2017-01-18 22:43 UTC, twhnat commented on .idea/modules.xml
>    <component name="ProjectModuleManager">
Add to .gitignore

2017-01-19 22:37 UTC, nasirali1 commented
Fixed the issues and removed config files. let me know if it works.

2017-01-19 22:37 UTC, closed without merging