Major update
MD2Korg/CerebralCortex-2.0-legacy pull request #51
Opened 2017-04-25 05:17 UTC by nasirali1

1 - Updated data-store read/write feature
2 - Added test-cases for date-store read/write feature
3 - Added data-diagnostic module
4 - Updated data-types schema

2017-04-28 16:23 UTC, twhnat requested changes
Here are some initial comments and changes.  We can talk about the write semantics later today

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/CerebralCortex.py
> +    def get_datastream(self, stream_identifier, start_time: datetime = None, end_time: datetime = None, data_type="all"):
Why does data_type default to a string of "all".  Should this become an enumeration?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/attachment_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Wrong year

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/attachment_marker.py
> +def attachment_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Please specify the return type and document the return value

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/attachment_marker.py
> +#TO-DO gsr_response method is not being used. Need to make sure whether GSR values actually respresent GSR data.
Please resolve TODO.  @monowar or @nsaleheen should know the answer.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/battery_data_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Year incorrect

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/battery_data_marker.py
> +def battery_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Please specify the return type and document the return value

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/battery_data_marker.py
> +    store(input_streams, merged_windows, CC_obj, config, config["algo_names"]["battery_marker"])
This storage semantic needs discussed.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/packet_loss_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Year

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/packet_loss_marker.py
> +def packet_loss_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Please specify the return type and document the return value

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +# Copyright (c) 2016, MD2K Center of Excellence
year

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +    CC_obj.save_datastream(ds)
Actually, we need to discuss this component specifically.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def store(input_streams: dict, data: OrderedDict, CC_obj: CerebralCortex, config: dict, algo_type: str):
Please specify the return type and document the return value

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_data_descriptor(algo_type, config):
Can this be better abstracted into a general method that is placed in the main kernel?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_execution_context(name: str, input_param: dict, input_streams: dict, output_streams: dict, method: str,
Can this be abstracted and moved to the main kernel

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_annotations():
Seems to have no purpose?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Year

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +def wireless_disconnection(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Please specify the return type and document the return value

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +    #battery_off_data = CC_obj.get_datastream(battery_off_stream_id, data_type="data")
Remove commented code

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +def autosense_calculate_magnitude(accel_x: float, accel_y: float, accel_z: float) -> list:
Are these functions already implemented in data_processor?  If not, maybe they should be moved there or you can just utilize them directly.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Year

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def write_to_csv(data: OrderedDict, file_name):
This is machine specific, either generalize and move to the kernel as an alternative output mechanism or remove

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def datetime_to_epoch(date_obj):
This is timezone specific, remove or generalize

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def map_data_to_datapoints(data: list) -> DataPoint:
Why do you have data that is not already in datapoint format?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def motionsense_magnitude(accel_xyz: List[DataPoint]) -> DataPoint:
Duplicate code from the previous file.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +    # if start_time != None:
Remove commented code, confusing.

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def get_stream_data(stream_id: uuid, CC_obj: CerebralCortex, start_time: datetime=None, end_time: datetime=None, data_type: str="all") -> Stream:
Do you really need a dedicated function for this?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +    def get_stream(self, stream_id: uuid, start_time: datetime = None, end_time: datetime = None, data_type="all") -> DataStream:
Can data_type be an Enum?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +        stream_id = stream_id
Does nothing

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +            localtz = timezone('US/Central')
Can't make this assumption

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +        #description = datastream_info[0][3]
Remove

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +    @staticmethod
Relocate to the kernel, this is used all the time across the sytem

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Data/StoreData.py
>      def store_data(self, dataframe_data: object, table_name: str):
This need discussed

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/DataStoreEngine/Metadata/StoreMetadata.py
> +        exe = 0
What does this variable do?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +                 #description: str = None,
Remove or undo comment

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/datatypes/datastream.py
> +                 stream_type: str = None,
Enumeration?

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/datatypes/stream.py
> +    #Ali: rename to owner?
yes

2017-04-28 16:23 UTC, twhnat commented on cerebralcortex/kernel/datatypes/stream.py
> +    #Ali: remove?
I think the description is still part of the datastream defination

2017-04-28 16:48 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/attachment_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 16:49 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/attachment_marker.py
> +def attachment_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Doesn't return anything

2017-04-28 16:50 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/battery_data_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 16:50 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/battery_data_marker.py
> +def battery_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Doesn't return anything

2017-04-28 16:51 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/packet_loss_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 16:51 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/packet_loss_marker.py
> +def packet_loss_marker(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Doesn't return anything

2017-04-28 16:51 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 16:51 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def store(input_streams: dict, data: OrderedDict, CC_obj: CerebralCortex, config: dict, algo_type: str):
Doesn't return anything

2017-04-28 16:56 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_data_descriptor(algo_type, config):
These are algorithm specific. Each algo/module has to define (set/get) their own descriptor.

2017-04-28 16:56 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_execution_context(name: str, input_param: dict, input_streams: dict, output_streams: dict, method: str,
These are algorithm specific. Each algo/module has to define (set/get) their own descriptor.

2017-04-28 16:56 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_annotations():
It is there for the sake of completeness.

2017-04-28 16:56 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 16:57 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +def wireless_disconnection(stream_id: uuid, CC_obj: CerebralCortex, config: dict, start_time=None, end_time=None):
Doesn't return anything

2017-04-28 16:58 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +    #battery_off_data = CC_obj.get_datastream(battery_off_stream_id, data_type="data")
Fixed

2017-04-28 17:03 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/sensor_unavailable_marker.py
> +def autosense_calculate_magnitude(accel_x: float, accel_y: float, accel_z: float) -> list:
It depends, for motionsense, yes (from cerebralcortex.data_processor.signalprocessing.vector) but I am not sure this can handle autosense accelerator.

2017-04-28 17:04 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +# Copyright (c) 2016, MD2K Center of Excellence
Fixed

2017-04-28 17:05 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def datetime_to_epoch(date_obj):
Fixed

2017-04-28 17:05 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def write_to_csv(data: OrderedDict, file_name):
Removed

2017-04-28 17:09 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def map_data_to_datapoints(data: list) -> DataPoint:
Removed.

2017-04-28 17:10 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def motionsense_magnitude(accel_xyz: List[DataPoint]) -> DataPoint:
Which previous file?

2017-04-28 17:18 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def get_stream_data(stream_id: uuid, CC_obj: CerebralCortex, start_time: datetime=None, end_time: datetime=None, data_type: str="all") -> Stream:
Nope. to-do (needs bit of refactoring).

2017-04-28 17:18 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +    # if start_time != None:
Fixed

2017-04-28 17:18 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +    def get_stream(self, stream_id: uuid, start_time: datetime = None, end_time: datetime = None, data_type="all") -> DataStream:
Not sure, what you mean. Let's discuss

2017-04-28 17:20 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +        stream_id = stream_id
Fixed

2017-04-28 17:20 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +            localtz = timezone('US/Central')
Let's discuss.

2017-04-28 17:22 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +        #description = datastream_info[0][3]
Removed commented code.

2017-04-28 17:23 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +    @staticmethod
Not sure, what you mean. discuss.

2017-04-28 17:24 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Metadata/StoreMetadata.py
> +        exe = 0
It handles mysql connection. It is a workaround to avoid opening/closing multiple connections.

2017-04-28 17:25 UTC, nasirali1 commented on cerebralcortex/kernel/datatypes/datastream.py
> +                 stream_type: str = None,
Let's discuss

2017-04-28 17:25 UTC, nasirali1 commented on cerebralcortex/kernel/datatypes/stream.py
> +    #Ali: rename to owner?
Fixed.

2017-04-28 17:26 UTC, nasirali1 commented on cerebralcortex/kernel/datatypes/stream.py
> +    #Ali: remove?
It is redundant. We have this information in "metadata" of a stream.

2017-04-28 21:02 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/LoadData.py
> +    @staticmethod
Fixed

2017-04-28 21:03 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Data/StoreData.py
>      def store_data(self, dataframe_data: object, table_name: str):
Fixed

2017-04-28 21:04 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/post_processing.py
> +def get_execution_context(name: str, input_param: dict, input_streams: dict, output_streams: dict, method: str,
TO-DO, make it into objects

2017-04-28 21:12 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Metadata/StoreMetadata.py
> +        exe = 0
Rename variable to more descriptive

2017-05-02 00:26 UTC, nasirali1 commented on cerebralcortex/data_processor/data_diagnostic/util.py
> +def get_stream_data(stream_id: uuid, CC_obj: CerebralCortex, start_time: datetime=None, end_time: datetime=None, data_type: str="all") -> Stream:
Fixed

2017-05-02 00:31 UTC, nasirali1 commented on cerebralcortex/kernel/DataStoreEngine/Metadata/StoreMetadata.py
> +        exe = 0
Fixed

2017-05-03 15:57 UTC, twhnat approved these changes

2017-05-03 15:59 UTC, merged